celebritea/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('teas/', views.teas_index, name='index'),
  path('teas/<int:tea_id>/', views.teas_detail, name='detail'),
  path('teas/create/', views.TeaCreate.as_view(), name='teas_create'),
  path('teas/<int:pk>/update/', views.TeaUpdate.as_view(), name='teas_update'),
  path('teas/<int:pk>/delete/', views.TeaDelete.as_view(), name='teas_delete'),
  path('teas/<int:tea_id>/add_sighting/', views.add_sighting, name='add_sighting'),
  path('celebs/', views.celebs_index, name='index'),
  path('celebs/<int:celeb_id>/', views.celebs_detail, name='celebs_detail'),
  path('celebs/create/', views.CelebCreate.as_view(), name='celebs_create'),
  path('celebs/<int:pk>/update/', views.CelebUpdate.as_view(), name='celebs_update'),
  path('celebs/<int:pk>/delete/', views.CelebDelete.as_view(), name='celebs_delete'),
  path('teas/<int:tea_id>/add_sighting/', views.add_sighting, name='add_sighting'),
  path('teas/<int:tea_id>/assoc_celeb/<int:celeb_id>/', views.assoc_celeb, name='assoc_celeb'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

TIME = (
    ('D','Dawn'),
    ('N','Noon'),
    ('A','Afternoon'),
    ('E','Evening'),
    ('L','Latenight')
)
class Celeb(models.Model):
    name= models.CharField(max_length=50)
    description= models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('celebs_detail', kwargs={'pk': self.id})

class Tea(models.Model):
    title = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    witnesses = models.IntegerField()
    celebs = models.ManyToManyField(Celeb)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'tea_id': self.id})

class Sighting(models.Model):
  date = models.DateField('Sighting Date')
  time = models.CharField('Time of day',
    max_length=1,
    choices=TIME,
    default=TIME[0][0]
  )
  tea = models.ForeignKey(Tea, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_time_display()} on {self.date}"

#   class Meta:
#     ordering=['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Sighting

class SightingForm(ModelForm):
  class Meta:
    model = Sighting
    fields = ['date', 'time']

main_app/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from main_app.models import Tea, Celeb
from main_app.forms import SightingForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def assoc_celeb(request, tea_id, celeb_id):
  # Note that you can pass a toy's id instead of the whole object
  Tea.objects.get(id=tea_id).celebs.add(celeb_id)
  return redirect('detail', tea_id=tea_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def teas_index(request):
    teas = Tea.objects.filter(user=request.user)
    return render(request, 'teas/index.html', { 'teas': teas})

@login_required
def teas_detail(request, tea_id):
    tea = Tea.objects.get(id=tea_id)
    celebs_tea_doesnt_have = Celeb.objects.exclude(id__in = tea.celebs.all().values_list('id'))
    sighting_form = SightingForm()
    return render(request, 'teas/detail.html', {
        'tea': tea, 'sighting_form':sighting_form, 
        'celebs': celebs_tea_doesnt_have
        })

@login_required
def add_sighting(request, tea_id):
    form = SightingForm(request.POST)
    if form.is_valid():
        new_sighting = form.save(commit=False)
        new_sighting.tea_id = tea_id
        new_sighting.save()
    return redirect('detail', tea_id=tea_id)


class TeaCreate(LoginRequiredMixin, CreateView):
  model = Tea
  fields = ['title', 'type', 'description', 'witnesses']
  def form_valid(self,form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class TeaUpdate(LoginRequiredMixin, UpdateView):
  model = Tea
  fields = ['title', 'description', 'witnesses']

class TeaDelete(LoginRequiredMixin, DeleteView):
  model = Tea
  success_url = '/teas/'

@login_required
def celebs_index(request):
    celebs = Celeb.objects.all()
    return render(request, 'celebs/index.html', {'celebs': celebs})

@login_required
def celebs_detail(request, celeb_id):
  celeb = Celeb.objects.get(id=celeb_id)
  return render(request, 'celebs/detail.html', { 'celeb': celeb })

class CelebCreate(LoginRequiredMixin, CreateView):
  model = Celeb
  fields = ['name', 'description']
  success_url = '/celebs/'


class CelebUpdate(LoginRequiredMixin, UpdateView):
  model = Celeb
  fields = ['name','description']
  success_url = '/celebs/'

class CelebDelete(LoginRequiredMixin, DeleteView):
  model = Celeb
  success_url = '/celebs/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

    <img src="../static/images/CELEBLOGO.png">
    <hr />
    <H1>So What Is <img class="aboutlogo" src="../static/images/CELEBLOGO.png"> about?</H1>
    </br>
    </br>
    <p class="aboutp">The Honest truth is that there is nothing better than making fun of celebrities with huge egoes, or maybe even making fun jokes about our favorite celebrities!</br>Again, any and all pieces of content on this site are a work of fiction and should NOT be taken seriously... seriously please don't sue me.</p>

{% endblock %}    

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>CelebriTea</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="grey darken-4">
        <div class="nav-wrapper">
          <div class="container">
          <ul>
            <li>
              <a href="/" class="left brand-logo"> <img class="logoimage" src="../static/images/CELEBLOGO.png"> </a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'teas_create' %}">Spill Some Tea</a></li>
            <li><a href="/teas">Spilt Tea</a></li>
            <li><a href="{% url 'celebs_create' %}">Add a Celebrity</a></li>
            <li><a href="/celebs">View All Celebrities</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer grey darken-4">
      <div class="container">
      <div class="left">
      </div>
      <div class="center">
        <img class='footlogo' src="../static/images/Screen Shot 2022-10-26 at 12.01.56 AM.png"> 
      </div>
      </div>
    </footer>
  </body>
</html>

main_app/templates/celebs/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Celeb Details</h1>


<div class="card">
        <div class="card-content">
            <span class="card-title">A {{celeb.description}} {{ celeb.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'celebs_update' celeb.id %}">Edit</a>
            <a href="{% url 'celebs_delete' celeb.id %}">Delete</a>
        </div>
</div>

{% endblock %}

main_app/templates/celebs/index.html
{% extends 'base.html' %}

{% block content %}
<img src="../static/images/CELEBLOGO.png">
<hr />
<h1 class="celeblistheader">My Celeb List</h1>
{% for celeb in celebs %}
<div class="card">
    <a class="text" href="/celebs/{{ celeb.id }}">
        <div class="card-content">
            <span class="card-title">A {{ celeb.description }} {{ celeb.name }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<body class="homebody">
<image src="../static/images/warning.png"></image>
</body>
{% endblock %}

main_app/templates/main_app/celeb_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Celebrity?</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes, They will Sue me!">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/celeb_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1 class="celebformhead">Update {{ object.name }}</h1><hr />
{% else %}
    <h1 class="celebformhead">Add Celeb</h1><hr />
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Celeb {% else %} Add Celeb {% endif %}">
</form>

{% endblock %}

main_app/templates/main_app/tea_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Did you spill too much?</h1>

<h4>
  Are you sure you want to clean the
  <span class="teal-text">"{{ object.title }}"</span> tea?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Im afraid of getting sued" class="btn" />
  <a href="{% url 'detail' tea.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/tea_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}
<h1 class="teaheader">Got More Detials For {{object.title}}?</h1><hr />
{% else %}
<h1 class="teaheader"><span class="red-text">Breaking News?</span></h1><hr />
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input  type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/teas/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="teaindextext">The Tea is Hot!</h1><hr />

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ tea.title}}</span>
        <h5><strong>First Impression...</strong> {{ tea.type }}</h5>
        <p><strong>So What Happened?:</strong> {{ tea.description }}</p>
        {% if tea.witnesses > 7 %}
        <h6>There were <strong>{{ tea.witnesses }}</strong> witnesses!</h6>
        {% else %}
        <h6>Only <strong>{{ tea.witnesses }}</strong> people witnessed this?</h6>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'teas_update' tea.id %}">Edit</a>
        <a href="{% url 'teas_delete' tea.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
      <form action="{% url 'add_sighting' tea.id %}" method="post">
        {% csrf_token %} {{ sighting_form.as_p }}
        <input type="submit" class="btn" value="Add Sighting" />
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Time Of Day</th>
          </tr>
        </thead>
        <tbody>
          {% for sighting in tea.sighting_set.all %}
          <tr>
            <td>{{sighting.date}}</td>
            <td>{{sighting.get_time_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h5>Celebrities involved in the {{ tea.title }} incident</h5>
    {% if tea.celebs.count %} {% for celeb in tea.celebs.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A(n) {{ celeb.description }} {{celeb.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No celebrities were involved?</h5>
    {% endif %}
  </div>


  <div class="col s6">
    <h3>Other Listed Celebs</h3>
    {% if celebs.count %}
      {% for celeb in celebs.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A(n) {{ celeb.description }} {{ celeb.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_celeb' tea.id celeb.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{tea.name}} Already Has All Possible Celebrities listed</h5>
    {% endif %}
  </div>


  <script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    var selectEl = document.getElementById('id_time');
    M.FormSelect.init(selectEl);
  </script>
  {% endblock %}

main_app/templates/teas/index.html
{% extends 'base.html' %} {% block content %}

<img src="../static/images/CELEBLOGO.png">
<hr />
<h1 class="celeblistheader">My Reportings!</h1>

{% for tea in teas %}
<div class="card">
<a class="teatextindex"href="/teas/{{ tea.id }}">
  <div class="card-content">
    <span class="card-title">{{ tea.title}}</span>
    <h5><strong>First Impression...</strong> {{ tea.type }}</h5>
    <p><strong>So What Happened?:</strong> {{ tea.description }}</p>
    {% if tea.witnesses > 7 %}
    <h6>There were <strong>{{ tea.witnesses }}</strong> witnesses!</h6>
    {% else %}
    <h6>Only <strong>{{ tea.witnesses }}</strong> people witnessed this?</h6>
    {% endif %}
  </div>
  </a>
</div>
{% endfor %} {% endblock %}